### ISSUE TITLE
How to calculate mAP ?

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [tilemmpon/Singapore-Maritime-Dataset-Trained-Deep-Learning-Models#2]
Sir how do you evaluate both models? Keras_yolo and TensorFlow API?  The both project directories and your project do not contains any code to evaluate model i.e Precision , recall and mAP. Can you provide the code or links you used to calculate mAP?

**Comment by tilemmpon** [comment]
I apologize for the delayed reply.

For TensorFlow you can use TensorBoard, which visualizes the various versions of test data mAP during the training of the model. This is a very useful suite of tools and I suggest to use it.

For Keras YOLO, the API outputs the AP per class and the mAP after the training in the terminal from where it was run. This is a valid mAP from what I saw in the code.

In case you want to use the same code to generate the mAP for all models, then you must look into various github projects implementing mAP and use one of them. I have not written any code for mAP myself, but there are meany projects for mAP, such as https://github.com/Cartucho/mAP.

**Comment by MuhammadAsadJaved** [comment]
OK. Thank you sir,  Have you tried to run your models with TensorRT or Deepstream?

**Comment by tilemmpon** [comment]
Unfortunately, I have not tried these frameworks.
