### ISSUE TITLE
Update the model and .config 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [tilemmpon/Singapore-Maritime-Dataset-Trained-Deep-Learning-Models#3]
Hi Sir,  I think there is a mistake during uploading tensorflow models and relevant .config files for first two models.  Please update if I am right. 

![smdNew](https://user-images.githubusercontent.com/28862708/67918484-74833c00-fb94-11e9-8be8-c15e4e6cc872.png)

**Comment by tilemmpon** [comment]
Yes, it looks like there is a mistake. Thanks for pointing this out :) . I will correct it right away.
