### ISSUE TITLE
ssd_resnet_50_fpn_smd and ssd_resnet_50_fpn_smd_2 seem to be same.

### ISSUE THREAD

**Issue by dsgh2** [tilemmpon/Singapore-Maritime-Dataset-Trained-Deep-Learning-Models#4]
According to both .config file from each, These files seem to be same.

It would highly appreciate if you check it again.

Thanks in advance.

**Comment by tilemmpon** [comment]
Thank you for your time to review and inform me of this potential mistake.

They are the same, with the only difference that the dataset is different, see: https://github.com/tilemmpon/Singapore-Maritime-Dataset-Trained-Deep-Learning-Models/blob/252cf73b1408b96a4c0a803ecc45bdc2b531343c/tensorflow_training_configurations/faster_rcnn_resnet50_smd.config#L121.

 I did this to compare how the mAP of some models changes based on slightly different dataset.  For the two splits of the Singapore Maritime Dataset I used, please see https://github.com/tilemmpon/Singapore-Maritime-Dataset-Frames-Ground-Truth-Generation-and-Statistics.

**Comment by lchunleo** [comment]
Can advise how to load the non-yolo framework weights and parameter? thanks.

**Comment by tilemmpon** [comment]
In the README I refer you to the original Tensorflow Object Detection API tutorial in: https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb.
