### ISSUE TITLE
Backend backbone  unavailable

### ISSUE THREAD

**Issue by lchunleo** [tilemmpon/Singapore-Maritime-Dataset-Trained-Deep-Learning-Models#5]
Hi,

  Thank you for sharing your work. I tried to download the tiny_yolo_backend.h5 backbone but its seem unavailable? thank you

**Comment by tilemmpon** [comment]
You are correct, thanks for letting me know. I used the original authors' links to onedrive and he removed the models. I uploaded to my cloud and updated the links. They are available now.
