### ISSUE TITLE
Number of frames of 'MVI_0790_VIS_OB.avi' in 'objects_onboard.txt' does not match with that of the video clip

### ISSUE THREAD

**Issue by Qianna00** [tilemmpon/Singapore-Maritime-Dataset-Trained-Deep-Learning-Models#6]
When I capture the frames of 'MVI_0790_VIS_OB.avi' using cv2, I can obtain 600 image files in total, it seems natural because the fps  and length of the video clip are 30 and 20s respectively.
However, I found the image_name of frames in 'objects_onboard.txt' are listed as you can see in the following pictures.
Does that mean some frames of the video clip are lost and there are at least 894 frames in total?
![1](https://user-images.githubusercontent.com/41325698/86426843-45246080-bd1b-11ea-95d0-41643d22dfa3.PNG)
![2](https://user-images.githubusercontent.com/41325698/86426845-481f5100-bd1b-11ea-8200-0be2d2f8c421.PNG)
![3](https://user-images.githubusercontent.com/41325698/86426847-4a81ab00-bd1b-11ea-9cf1-aae70f008dd4.PNG)

**Comment by tilemmpon** [comment]
Hi Qianna00. Thanks for letting me know. I will look into it. However, this issue will close since it relates to the other repository (where you also posted it).
